### ISSUE TITLE
 package ‘pipelearner’ is not available (for R version 3.5.0)

### ISSUE THREAD

**Issue by PescheHelfer** [erblast/oetteR#18]
Hey Björn :)

I am trying to build the most recent version of oetteR (0.2.8). It depends on "pipelearner", but I fail to get the package for R version 3.5.0:
`install.packages("pipelearner")`
 package ‘pipelearner’ is not available (for R version 3.5.0)

Is there any workaround for this problem?
Thanks a lot and best regards
Pesche

**Comment by PescheHelfer** [comment]
Sorry, my bad. Pipelearner is just another git repo. Building it first and then building oetteR did the trick :)

**Comment by erblast** [comment]
Hey Pesche,

sorry just read your post, glad that you managed to solve it. I regret making pipelearner a dependency but it is too much work at the moment to take it out.

Hope all is well with you.

Cheers
